Main
genga911/yandexworkshop pull request #2
Opened 2022-02-07 18:31 UTC by genga911

Готовый сервис согласно требованиям инкремента 3 первые 3 автотеста пройдены

2022-02-09 18:48 UTC, ASPecherkin requested changes

2022-02-09 18:48 UTC, ASPecherkin commented on internal/app/constants/constants.go
> +const HOST = "localhost"
Так как в будущем эти параметры могут менять и их будет больше - лучше назвать пакет config, так как он отвечает за конфигурацию параметров приложения 

Сюда же можно перенести функции GetServerAddress, GetMainLink  , они тесно связаны с этой функциональностью  и данными

2022-02-09 18:48 UTC, ASPecherkin commented on internal/app/handlers/resolve.go
> +	store := c.MustGet("Store").(storages.Repository)
Передавать объекты для запроса через context можно, но лучше так не делать - считается плохой практикой. 

Почему: получение из context объекта - это происходящее в runtime событие, которое может привести к падению программы, о чём говорит и описание метода MustGet

Гораздо безопаснее сделать структуру вида 
```go
type StoreHandler struct {
	Storage storages.Repository
}
```
и уже у него реализовать метод Handle(c *gin.Context) и его использовать для передачи в router

В этом случае ты проверяешь соответствие типов уже на этапе компиляции и не нужно будет добавлять  в gin.Context большой объект 
Кроме того - такую структуру проще расширять

2022-02-09 18:48 UTC, ASPecherkin commented on internal/app/handlers/mocks/mock.go
> +func MockGinContext(w *httptest.ResponseRecorder, r *http.Request, store storages.Repository) *gin.Context {
Учитывая комментарий ниже - здесь можно будет убрать store storages.Repository и в тестах использовать конкретный экземпляр Handler и уже в него передавать mock storage-а

2022-02-09 18:48 UTC, ASPecherkin commented on internal/app/storages/storage.go
> +var Links *LinkStorage
лучше не использовать глобальные переменные 

Хороший подход - вызвать создание CreateLinkStorage в SetUpServer и уже его передавать в структуры обработчиков явно

2022-02-09 18:48 UTC, ASPecherkin commented on internal/app/storages/storage.go
> +func init() {
по итогу комментария выше , получаем не будет глобальной переменной - не понадобится делать такой init() - инициализация станет явной 
init() в go программах используется достаточно редко, и если есть возможность что-то сделать явно в main или другой функции - делают это там

2022-02-12 16:25 UTC, genga911 commented on internal/app/constants/constants.go
> +const HOST = "localhost"
заменил название пакета, перенес функции и тесты

2022-02-12 16:26 UTC, genga911 commented on internal/app/handlers/resolve.go
> +	store := c.MustGet("Store").(storages.Repository)
создал структуру, добавил обертки для методов. удалил middleware, переписал тесты

2022-02-12 16:26 UTC, genga911 commented on internal/app/handlers/mocks/mock.go
> +func MockGinContext(w *httptest.ResponseRecorder, r *http.Request, store storages.Repository) *gin.Context {
переписал функцию. удалил из аргументов store, добавил возможность устанавливать параметры в моке

2022-02-12 16:27 UTC, genga911 commented on internal/app/storages/storage.go
> +func init() {
удалил инит за ненадобностью

2022-02-14 10:09 UTC, genga911 commented on internal/app/storages/storage.go
> +var Links *LinkStorage
удалил глобальную переменную

2022-02-14 17:38 UTC, ASPecherkin commented
Проделана хорошая работа, продолжай в том же духе!
Осталась небольшая мелочь и можно будет принимать работу

2022-02-15 08:51 UTC, ASPecherkin requested changes

2022-02-15 08:51 UTC, ASPecherkin commented on internal/app/handlers/router_handler.go
> +func (rh *RouterHandlers) GetHandler(c *gin.Context) {
Скорее всего я не был точен в формулировках на прошлом ревью, моё упущение. 

Когда я говорил об отельных handler-ах , я имел в виду отдельную структуру под каждый метод, который будет реализовывать твой сервис.

Может возникнуть резонный вопрос - зачем так, если у нас сейчас они одинаковые?

Тут вопрос изоляции и модульности - предположим, что POST у нас пишет в другую базу, которая доступна для записи, а GET читает из оптимизированного под чтение хранилища. 

В такой композиции кода - нам понадобится добавить ещё один Repository в общую структуру RouterHandlers, но нужен он будет только одному методу у этой структуры. 

Как раз , чтобы максимально сузить зону отвественности и количество зависимостей для каждого hander-а, лучше их разделить на отдельные структуры / пакеты

2022-02-15 14:27 UTC, genga911 commented on internal/app/handlers/router_handler.go
> +func (rh *RouterHandlers) GetHandler(c *gin.Context) {
добавил структуры для каждого роута

2022-02-15 18:05 UTC, ASPecherkin approved these changes

2022-02-19 12:10 UTC, merged