Инкремент 4
genga911/yandexworkshop pull request #3
Opened 2022-02-19 12:23 UTC by genga911

2022-02-21 19:04 UTC, ASPecherkin requested changes
В целом всё хорошо, есть мелкие проблемы которые нужно поправить

2022-02-21 19:04 UTC, ASPecherkin commented on internal/app/storages/storage.go
>  		ls.store[key] = shortLink
наверно не заметил в первом ревью - так как используется обычный map без mutex, то может произойти следующая проблема 
при конкурентной записи в map , если будет несколько запросов одновременно,  произойдёт паника 
описание есть тут https://stackoverflow.com/questions/45585589/golang-fatal-error-concurrent-map-read-and-map-write

Лучше всего такое решать с помощью sync.RWMutex

2022-02-21 19:04 UTC, ASPecherkin commented on internal/app/handlers/store.go
> +	c.String(http.StatusCreated, string(encode))
можно упростить  до 
```go
result.Result = shortedLink
c.JSON(http.StatusCreated, result)
```

2022-02-22 07:14 UTC, genga911 commented on internal/app/handlers/store.go
> +	c.String(http.StatusCreated, string(encode))
так у меня изначально и было, но из за этого падают тесты так как в моем коде перестает использоваться пакет json, а его использование судя по всему обязательно для данного этапа обучения

2022-02-22 07:16 UTC, genga911 commented on internal/app/handlers/store.go
> +	c.String(http.StatusCreated, string(encode))
вот пруф
![image](https://user-images.githubusercontent.com/24940967/155081527-e19016d3-adbf-470c-b100-6c3c13699e38.png)

вот ссылка на тесты https://github.com/genga911/yandexworkshop/runs/5258540954?check_suite_focus=true

2022-02-22 14:24 UTC, genga911 commented on internal/app/storages/storage.go
>  		ls.store[key] = shortLink
я изучил этот вопрос и внес изменения в код, но обучающий материал пока не затрагивал тему мьютексов, гонки, рутин и всего остального связанного с многопоточностью, я смею предположить что об этом вероятно будет написано далее, и сейчас применение этого в коде выглядит как небольшой забегание вперед

2022-02-22 20:18 UTC, ASPecherkin commented on internal/app/handlers/store.go
> +	c.String(http.StatusCreated, string(encode))
Благодарю, учту и донесу это до составителей тестов 👍

2022-02-22 20:19 UTC, ASPecherkin commented on internal/app/storages/storage.go
>  		ls.store[key] = shortLink
Отлично , спасибо тебе за желание самому разобраться, похвально 👍 

Да, но будет в будущих темах, но глаз зацепился уже профессионально

2022-02-22 20:20 UTC, ASPecherkin approved these changes

2022-02-22 21:40 UTC, merged